---
- name: Deploy to Production
  hosts: localhost
  become: true

  vars: 
    project_dir: /var/lib/jenkins/workspace/flask-postgre-project

  tasks:
    - name: Ensure APT cache is updated
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Install Docker using official convenience script
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        creates: /usr/bin/docker

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Ensure Docker is running
      systemd:
        name: docker
        state: started
        enabled: true 

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: "{{ project_dir }}"
