version: "3.8"

services:
  web:
    image: python:3.11
    container_name: flask_web
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - SECRET_KEY
      - DATABASE_URL=postgresql://myuser:mypass@db:5432/mydb
    command:
      - sh
      - -c
      - |
        pip install --upgrade pip
        pip install -r requirements.txt
        python -c "from main import db; db.create_all()"  # ✅ Create tables
        python main.py  # ✅ Start Flask app

  db:
    image: postgres:16
    container_name: flask_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8000:80"
    depends_on:
      - web
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

volumes:
  postgres_data:
